server:
  port: 30001
spring:
  application:
    name: alex-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #启动自动根据服务id生成路由
          lower-case-service-id: true #设置路由的路径为小写的服务id
      routes:
        - id: alex-mission
          uri: lb://alex-mission
          predicates:
            - Path=/alex-mission/**
          filters:
            - StripPrefix=1 #移除前缀
        #            - name: RequestRateLimiter
        #              args:
        #                redis-rate-limiter.replenishRate: 10
        #                redis-rate-limiter.burstCapacity: 20

        - id: alex-user
          uri: lb://alex-user
          predicates:
            - Path=/alex-user/**
          filters:
            - StripPrefix=1
  #
  #        - id: alex-manage
  #          uri: lb://alex-manage
  #          predicates:
  #            - Path=/alex-manage/**
  #          filters:
  #            - StripPrefix=1
  #
  #        - id: alex-monitor
  #          uri: lb://alex-monitor
  #          predicates:
  #            - Path=/alex-monitor/**
  #          filters:
  #            - StripPrefix=1

management:
  endpoints:
    #   在访问/actuator/health时显示完整信息
    logfile:
      external-file: log/alex-gateway/gateway.log
logging:
  # 日志文件地址
  config: classpath:logback-spring.xml
  level:
    org.springframework.cloud.gateway: debug