server:
  port: 30001
spring:
  application:
    name: alex-gateway
  boot:
    admin:
      client:
#        url: http://localhost:30099
        instance:
          service-url: http://localhost:${server.port}
          name: ${spring.application.name}
  #        username: admin
#        password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}
        group: ${nacos.group}
        namespace: ${nacos.namaspace}
      server-addr: ${nacos.url}
    gateway:
      discovery:
        locator:
          enabled: true #启动自动根据服务id生成路由
          lower-case-service-id: true #设置路由的路径为小写的服务id
          filters:
            # 保留原始请求的host头信息，并原封不动的转发出去，而不是被gateway的http客户端重置。
            - PreserveHostHeader
      routes:
        - id: alex-mission
          uri: lb://alex-mission
          predicates:
            - Path=/am-mission/**
          filters:
            - StripPrefix=1 #移除前缀
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20

        - id: alex-user
          uri: lb://alex-user
          predicates:
            - Path=/am-user/**
          filters:
            - StripPrefix=1
        - id: alex-finance
          uri: lb://alex-finance
          predicates:
            - Path=/am-finance/**
          filters:
            - StripPrefix=1
#
#        - id: alex-manage
#          uri: lb://alex-manage
#          predicates:
#            - Path=/am-manage/**
#          filters:
#            - StripPrefix=1
#
#        - id: alex-monitor
#          uri: lb://alex-monitor
#          predicates:
#            - Path=/aa-monitor/**
#          filters:
#            - StripPrefix=1
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 30000
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      # 开放指定节点 /actuator/（info, health, beans, env, metrics）或者全部
      exposure:
        include: '*'
#   在访问/actuator/health时显示完整信息
    logfile:
      external-file: log/alex-gateway/gateway.log
logging:
  # 日志文件地址
  config: classpath:logback-spring.xml

  level:
    org.springframework.cloud.gateway: debug

knife4j:
  enable: true
  production: false
#  basic:
#    enable: true
#    password: 123456
#    username: alex