server:
  port: 30001
spring:
  application:
    name: alex-gateway-prod
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #启动自动根据服务id生成路由
          lower-case-service-id: true #设置路由的路径为小写的服务id
          filters:
            # 保留原始请求的host头信息，并原封不动的转发出去，而不是被gateway的http客户端重置。
            - PreserveHostHeader
      routes:
        #移除前缀
        #            - name: RequestRateLimiter
        #              args:
        #                redis-rate-limiter.replenishRate: 10
        #                redis-rate-limiter.burstCapacity: 20

        - id: alex-user
          uri: lb://alex-user-prod
          predicates:
            - Path=/am-user/**
          filters:
            - StripPrefix=1

        - id: alex-finance
          uri: lb://alex-finance-prod
          predicates:
            - Path=/am-finance/**
          filters:
            - StripPrefix=1
        - id: alex-mission
          uri: lb://alex-mission-prod
          predicates:
            - Path=/am-mission/**
          filters:
            - StripPrefix=1

        - id: alex-oss
          uri: lb://alex-oss-prod
          predicates:
            - Path=/am-oss/**
          filters:
            - StripPrefix=1

        - id: alex-product
          uri: lb://alex-product-dev
          predicates:
            - Path=/am-product/**
          filters:
            - StripPrefix=1

  #
  #        - id: alex-manage
  #          uri: lb://alex-manage
  #          predicates:
  #            - Path=/am-manage/**
  #          filters:
  #            - StripPrefix=1
  #
  #        - id: alex-monitor
  #          uri: lb://alex-monitor
  #          predicates:
  #            - Path=/aa-monitor/**
  #          filters:
  #            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    #   在访问/actuator/health时显示完整信息
    logfile:
      external-file: log/alex-gateway/gateway.log

logging:
  # 日志文件地址
  config: classpath:logback-spring.xml
  level:
    org.springframework.cloud.gateway: debug