server:
  port: 30002

spring:
  application:
    name: alex-web
#  boot:
#    admin:
#      client:
#        instance:
#          name: ${spring.application.name}
#          service-url: http://192.168.161.1:${server.port}
#        url: http://localhost:30099
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
qiniu:
  accessKey: ENC(XEL2TdE7S3eBkI4lukdgHuP03m3FKV/NaCpUezk6z6KCR6UOo7UGmS8VXI2YlI/cDCXyuGbuqFw=)
  secretKey: ENC(RySyvFuZ+SfUDAVA0VSUX4fexjmQ1t/D45oADbkAkRMQdy0kQX+cF9uyRsh/BUzJciemr1GK610=)
  bucket: weiran1999
  domain: http://rel.weiran.ltd/

management:
  endpoints:
    web:
      # 开放指定节点 /actuator/（info, health, beans, env, metrics）或者全部
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS