server:
  port: 40002

spring:
  application:
    name: alex-web

qiniu:
  accessKey: ENC(XEL2TdE7S3eBkI4lukdgHuP03m3FKV/NaCpUezk6z6KCR6UOo7UGmS8VXI2YlI/cDCXyuGbuqFw=)
  secretKey: ENC(RySyvFuZ+SfUDAVA0VSUX4fexjmQ1t/D45oADbkAkRMQdy0kQX+cF9uyRsh/BUzJciemr1GK610=)
  bucket: weiran1999
  domain: http://rel.weiran.ltd/

mybatis-plus:
  mapper-locations: classpath:mappers/**.xml