server:
  port: 30008

spring:
  application:
    name: alex-finance-dev
  shardingsphere:
    datasource:
      name: master, slave1, slave2
      master:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://123.249.83.33:3336/alex_finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: ENC(wzGvorwuoFra8yDJA66Xfg==)
        password: ENC(TQ2oVKN42O4FWPbyKH7mCHBwhNc4xNhLZa2IBDN93TI=)
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://123.249.83.33:3316/alex_finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: ENC(wzGvorwuoFra8yDJA66Xfg==)
        password: ENC(TQ2oVKN42O4FWPbyKH7mCHBwhNc4xNhLZa2IBDN93TI=)
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://123.249.83.33:3326/alex_finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: ENC(wzGvorwuoFra8yDJA66Xfg==)
        password: ENC(TQ2oVKN42O4FWPbyKH7mCHBwhNc4xNhLZa2IBDN93TI=)
    sharding:
      master-slave-rules:
        master-test0: # 哪一个主节点
          master-datasource-name: master                                          # 指定主节点名字
          slave-data-source-names: slave1,slave2                                # 指定读节点名字,多个读节点用逗号分开
        # 配置从库选择策略，提供轮询与随机，这里选择用轮询
      masterslave:
        load-balance-algorithm-type: round_robin
      props:
        sql:
          show: true   # 日志显示SQL
    rules:
      dataSources:
        readwrite_ds:
          staticStrategy:
            writeDataSourceName: master
            readDataSourceNames:
              - slave1
              - slave2
          loadBalancerName: random
      loadBalancers:
        random:
          type: RANDOM

mybatis-plus:
  mapper-locations: classpath:com/alex/finance/mapper/**/*Mapper.xml

logging:
  level:
    com.alex.finance.mapper: debug

accountNotice:
  difDay: 2

wechat:
  #测试号信息中的appID
  appId: wxec93a0ddb72c8cff
  #测试号信息中的appsecret
  secret: 1240434ae0be6dc4b0ba979d7c1f9b7a
  #用户列表中的微信号id
  userId:
  #模板消息接口中模板ID
  templateId:
  #在一起的时间
  loveDate: 2022-05-20
  #生日
  birthday: 1994-02-10
  #彩虹屁平台apiKey
  rainbowKey: