kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: drone-miaosha # 定义流水线名称

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: build-package # 流水线名称
    image: maven:3.8-openjdk-17 # 定义创建容器的Docker镜像
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: maven-build
        path: /usr/local/soft/drone/alex_miaosha # 将应用打包好的Jar和执行脚本挂载出来
    commands:
      - mvn clean package -DskipTests=true -s settings.xml -B -U
      - mkdir /usr/local/soft/drone/alex_miaosha/monitor
      # 将打包后的jar包，拷贝到挂载目录
      - cp /drone/src/alex_miaosha_monitor/target/alex_miaosha_monitor-1.0-SNAPSHOT.jar  /usr/local/soft/drone/alex_miaosha/monitor/
      - cp /drone/src/alex_miaosha_finance/target/alex_miaosha_finance-1.0-SNAPSHOT.jar  /usr/local/soft/drone/alex_miaosha/
      - cp /drone/src/alex_miaosha_gateway/target/alex_miaosha_gateway-1.0-SNAPSHOT.jar  /usr/local/soft/drone/alex_miaosha/
      - cp /drone/src/alex_miaosha_mission/target/alex_miaosha_mission-1.0-SNAPSHOT.jar  /usr/local/soft/drone/alex_miaosha/
      - cp /drone/src/alex_miaosha_web/target/alex_miaosha_web-1.0-SNAPSHOT.jar  /usr/local/soft/drone/alex_miaosha/
      - cp /drone/src/alex_generator/target/alex_generator-1.0-SNAPSHOT.jar  /usr/local/soft/drone/alex_miaosha/
      # 将Dockerfile拷贝到挂载目录
      - cp /drone/src/alex_miaosha_monitor/Dockerfile /usr/local/soft/drone/alex_miaosha/monitor/

  - name: ssh
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      # 你服务器ip地址
      host: 192.168.10.32
      # 服务器端口号
      port: 22
      # 服务器账号
      username: root
      # 密码登入写法
      password:
        from_secret: ssh_password
      script:
        - cd /usr/local/soft/drone/alex_miaosha/monitor
        - ls
        - docker build  -t alex_miaosha-monitor:latest .
        - docker run -p 30099:30099 -v /home/logs:/usr/local/logs -d alex_miaosha-monitor:latest
volumes: # 定义流水线挂载目录，用于共享数据
  - name: maven-build
    host:
      path: /usr/local/soft/drone/alex_miaosha/   #jar包目录可以修改从宿主机中挂载的目录