server:
  port: 30006

spring:
  application:
    name: alex-user

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://123.249.83.33:3336/alex_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ENC(wzGvorwuoFra8yDJA66Xfg==)
    password: ENC(TQ2oVKN42O4FWPbyKH7mCHBwhNc4xNhLZa2IBDN93TI=)

mybatis-plus:
  mapper-locations: classpath*:com/alex/user/mapper/**/*Mapper.xml

logging:
  level:
    com.alex.user.mapper: debug

qiniu:
  accessKey: XEL2TdE7S3eBkI4lukdgHuP03m3FKV/NaCpUezk6z6KCR6UOo7UGmS8VXI2YlI/cDCXyuGbuqFw=
  secretKey: RySyvFuZ+SfUDAVA0VSUX4fexjmQ1t/D45oADbkAkRMQdy0kQX+cF9uyRsh/BUzJciemr1GK610=
  bucket: weiran1999
  domain: http://rel.weiran.ltd/

#设置jwt
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: mogublog
  expiresSecond: 3600000  #1个小时 3600
  refreshSecond: 3600
  tokenHead: bearer_
  tokenHeader: Authorization


isRememberMeExpiresSecond: 259200000 #记住密码三天

defaultPassword: "1234@com"