server:
  port: 30099
spring:
  application:
    name: alex-monitor
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}
        group: ${nacos.group}
        namespace: ${nacos.namaspace}
      server-addr: ${nacos.url}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  security:
#    user:
#      name: admin
#      password: 123456
management:
  endpoints:
    web:
      # 开放指定节点 /actuator/（info, health, beans, env, metrics）或者全部
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
