server:
  port: 40099
spring:
  application:
    name: alex-monitor
  boot:
    admin:
      ui:
        title: ${spring.application.name}
#  security:
#    user:
#      name: admin
#      password: 123456
management:
  endpoint:
    health:
      show-details: ALWAYS