server:
  port: 30022

spring:
  application:
    name: alex-generator-dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://123.249.83.33:3336/alex_oss?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mjzp.99147258369

mybatis:
  mapper-locations: classpath:com/alex/finance/mapper/**/*Mapper.xml

logging:
  level:
    com.alex.generator.mapper: debug
