server:
  port: 30022

spring:
  application:
    name: alex-generator

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://123.249.83.33:3306/alex_user
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:com/alex/finance/mapper/**/*Mapper.xml

logging:
  level:
    com.alex.generator.mapper: debug
