server:
  port: 30022

spring:
  application:
    name: alex-generator

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://nacos/alex_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ENC(wzGvorwuoFra8yDJA66Xfg==)
    password: ENC(TQ2oVKN42O4FWPbyKH7mCHBwhNc4xNhLZa2IBDN93TI=)

mybatis:
  mapper-locations: classpath:com/alex/finance/mapper/**/*Mapper.xml

generator:
  vue: false
  feign: false