server:
  port: 30022

spring:
  application:
    name: alex-generator-dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://123.249.83.33:3306/alex_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mjzp.99147258369

mybatis:
  mapper-locations: classpath:com/alex/finance/mapper/**/*Mapper.xml

logging:
  level:
    com.alex.generator.mapper: debug

generator:
  vue: true
  feign: true
  tablePrefix: t_
  logicDeleteColumnName: is_delete
  logicDeletePropertyName: isDelete
  superEntityColumns: id, creator, createTime, updater, updateTime, deleter, deleteTime, isDelete, operator, operateTime
  addSuperVoColumns: id, creator, createTime, updater, updateTime, deleter, deleteTime, isDelete, operator, operateTime
#  javaPath: G:\project\alex_miaosha
#  voPath:
#  feignPath:
#  vuePath: F:\alex\project\alex_miaosha_front\src\views
#  tsPath: F:\alex\project\alex_miaosha_front\src\api
  parentPackage: com.alex

  javaPath: D:\project\alex_miaosha
  voPath:
  feignPath:
  vuePath: D:\project\alex_miaosha_front\src\views
  tsPath: D:\project\alex_miaosha_front\src\api