server:
  port: 40010

spring:
  application:
    name: alex-mission

  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        keep-alive: 60s
        queue-capacity: 1000
      thread-name-prefix: async-task-
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 30000 # 连接超时时间（毫秒）

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://localhost:3306/alex_miaosha?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mysql


qiniu:
  accessKey: ENC(XEL2TdE7S3eBkI4lukdgHuP03m3FKV/NaCpUezk6z6KCR6UOo7UGmS8VXI2YlI/cDCXyuGbuqFw=)
  secretKey: ENC(RySyvFuZ+SfUDAVA0VSUX4fexjmQ1t/D45oADbkAkRMQdy0kQX+cF9uyRsh/BUzJciemr1GK610=)
  bucket: weiran1999
  domain: http://rel.weiran.ltd/

logging:
  level:
    com.alex.mission.mapper: debug

knife4j:
  # 开启增强配置
  enable: true
#  # 开启生产环境屏蔽
#  production: false
#  enableAggregation: true
#  nacos:
#    enable: true
#    serviceUrl: http://localhost:8848/nacos/
#    routeAuth:
#      enable: true
#      username: test
#      password: 12313
#    routes:
#      - name: 订单服务
#        serviceName: alex-mission
#        groupName: alex-miaosha
#        namespaceId: 033377eb-973b-4dac-a0e9-e99c87325009
##        clusters: test
#        location: /v2/api-docs?group=default
#        swaggerVersion: 2.0
#        servicePath: /goods
#        routeAuth:
#          enable: true
#          username: test
#          password: 12313