server:
  port: 30005

spring:
  application:
    name: alex-mission
  boot:
    admin:
      client:
        url: http://localhost:30099
        instance:
          service-url: http://localhost:${server.port}
          name: ${spring.application.name}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        keep-alive: 60s
        queue-capacity: 1000
      thread-name-prefix: async-task-
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 30000 # 连接超时时间（毫秒）

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://localhost:3306/alex_miaosha?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mysql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

qiniu:
  accessKey: ENC(XEL2TdE7S3eBkI4lukdgHuP03m3FKV/NaCpUezk6z6KCR6UOo7UGmS8VXI2YlI/cDCXyuGbuqFw=)
  secretKey: ENC(RySyvFuZ+SfUDAVA0VSUX4fexjmQ1t/D45oADbkAkRMQdy0kQX+cF9uyRsh/BUzJciemr1GK610=)
  bucket: weiran1999
  domain: http://rel.weiran.ltd/

logging:
  level:
    com.alex.mission.mapper: debug

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
    #   在访问/actuator/health时显示完整信息