server:
  port: 30009

spring:
  application:
    name: alex-osssys

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://123.249.83.33:3306/alex_oss?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ENC(wzGvorwuoFra8yDJA66Xfg==)
    password: ENC(TQ2oVKN42O4FWPbyKH7mCHBwhNc4xNhLZa2IBDN93TI=)

mybatis-plus:
  mapper-locations: classpath*:com/alex/osssys/mapper/**/*Mapper.xml

garage:
  url: garage
  port: 3900
  accessKey: GK453146754fe421b2fd6664fc
  secretKey: 3f0fb8b2db7d251b79d16acf6b60a6618f89a0f745e5757af50468aa16d49010
  bucketName: alex-miaosha
  region: garage