server:
  port: 30008

spring:
  application:
    name: alex-finance
  boot:
    admin:
      client:
        url: http://localhost:30099
        instance:
          service-url: http://localhost:${server.port}
          name: ${spring.application.name}
#          username: admin
#          password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://localhost:3306/alex_finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: mysql

management:
  endpoints:
    web:
      exposure:
        include: '*'
    #   在访问/actuator/health时显示完整信息
mybatis-plus:
  mapper-locations: classpath:com/alex/finance/mapper/**/*Mapper.xml

#配置knife4j
knife4j:
  #开启增强
  enable: true
  production: false

logging:
  level:
    com.alex.finance.mapper: debug
