server:
  port: 30006

spring:
  application:
    name: alex-user-dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://123.249.83.33:3306/alex_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ENC(wzGvorwuoFra8yDJA66Xfg==)
    password: ENC(TQ2oVKN42O4FWPbyKH7mCHBwhNc4xNhLZa2IBDN93TI=)

mybatis-plus:
  mapper-locations: classpath*:com/alex/user/mapper/**/*Mapper.xml

logging:
  level:
    com.alex.user.mapper: debug

isRememberMeExpiresSecond: 259200000 #记住密码三天

defaultPassword: "1234@com"